### PR TITLE
Use replace instead of remove+add on ObservableCollectionAdaptor.DoUpdate

### PR DESCRIPTION
**Pull request by wilversings**
**What kind of change does this PR introduce?**
Bug fix

**What is the current behavior?**
https://github.com/reactiveui/DynamicData/issues/378

**What is the new behavior?**
ObservableCollectionAdaptor will use the Replace ext method in order to trigger a
NotifyCollectionChangedAction.Replace event action type

**What might this PR break?**
Uses that rely on this behavior: https://github.com/reactiveui/DynamicData/issues/378

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [not needed] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/reactiveui/DynamicData?pullRequest=381) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/reactiveui/DynamicData?pullRequest=381) before we can accept your contribution.<br/><br/>:x: wilversings [sign now](https://cla.dotnetfoundation.org/reactiveui/DynamicData?pullRequest=381)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/reactiveui/DynamicData?pullRequest=381) it.</sub>

**Comment by RolandPheasant** [comment]
The change looks good. It can be merged, but can you sign the contributor license agreement agreement please?

**Comment by wilversings** [comment]
Yes, only need to check with my employer first.

**Comment by robsonj** [comment]
Hi There,

This change unfortunately breaks our DataGrid (Infragistics)...

Have been tracking down an issue with one of our UI's that is backed with ReactiveUI and DD, its a datagrid that has some some grouping, grouped on a status within the domain object. If the state value of the domain object changes, the item regroups to the appropriate state based group. Works perfectly with DD 6.16.2, but does not work with 6.16.3, I think this relates to this change in behaviour.

I also pulled in this code to our own code base, to verifying that reverting this one change, fixes the issue, which it did.

**Pull request merged**
