### PR TITLE
Fix for distinct calculator with duplicate keys

### LINKED ISSUE #273: [BUG] DistinctCalculator bug with duplicate items (keys)
**Describe the bug**
When using DistinctValues() adding the same item or key twice (two sources via Merge), then removing it from one source followed by refreshing or updating it from another source causes a crash (KeyNotFoundException)

The main problem is that the item is removed immediately from the internal cache (_itemCache in DistinctCalculator) when it is removed from source 2. Then when the item is updated or refreshed in source 1 it looks in the cache without checking if it is already in there.

One solution is to 'reference' count the keys just like the values in order to handle duplicate keys as well as values. We need to keep the item in the cache until the last remove in order to compare previous values on update or refresh. I'll have a pull request with this shortly.

**Steps To Reproduce**
1. Merge two sources
2. Apply distinct values
3. Add item A to both source 1 and 2
4. Remove item A from source 2
5. Update or refresh item A on source 1
6. KeyNotFoundException

**Expected behavior**
1. No exception should occur, 
2. No changes pushed out assuming item A value remains unchanged

**Environment**
- OS:       Win10
- Version   6.13.1

**Additional context**
Failing test:
```        
[Fact]
public void DuplicateKeysRefreshAfterRemove()
{
    var source1 = new SourceCache<Person, string>(p => p.Name);
    var source2 = new SourceCache<Person, string>(p => p.Name);

    var person = new Person("Person2", 12);

    var results = source1.Connect().Merge(source2.Connect()).DistinctValues(p => p.Age).AsAggregator();

    source1.AddOrUpdate(person);
    source2.AddOrUpdate(person);
    source2.Remove(person);
    source1.Refresh(person); // would previously throw KeyNotFoundException here

    results.Messages.Should().HaveCount(1);
    results.Data.Items.ShouldAllBeEquivalentTo(new[] {12});

    source1.Remove(person);

    results.Messages.Should().HaveCount(2);
    results.Data.Items.Should().BeEmpty();
}
```

### PR DESCRIPTION
**Pull request by lummoj**
**What kind of change does this PR introduce?**
Fixes #273 

**What is the current behavior?**
Exception with duplicate keys as described in issue

**What is the new behavior?**
Exception resolved, new unit test added

**What might this PR break?**
No change to existing functionality, all unit tests pass

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:
Not sure what documentation I need to update for this bug fix

### CODE REVIEW

**Comment by glennawatson** [comment]
Just some analyzers picking up some errors there

```
Cache\Internal\DistinctCalculator.cs(54,39): error RCS1037: Remove trailing white-space. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
Cache\Internal\DistinctCalculator.cs(62,35): error RCS1037: Remove trailing white-space. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
List\Internal\DynamicCombiner.cs(139,31): warning CA2208: Method UpdateResultList passes 'Reason' as the paramName argument to a ArgumentOutOfRangeException constructor. Replace this argument with one of the method's parameter names. Note that the provided parameter name should have the exact casing as declared on the method. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
List\Internal\Combiner.cs(127,31): warning CA2208: Method UpdateResultList passes 'Reason' as the paramName argument to a ArgumentOutOfRangeException constructor. Replace this argument with one of the method's parameter names. Note that the provided parameter name should have the exact casing as declared on the method. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
Cache\Internal\DistinctCalculator.cs(54,39): error RCS1037: Remove trailing white-space. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
Cache\Internal\DistinctCalculator.cs(62,35): error RCS1037: Remove trailing white-space. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
List\Internal\DynamicCombiner.cs(139,31): warning CA2208: Method UpdateResultList passes 'Reason' as the paramName argument to a ArgumentOutOfRangeException constructor. Replace this argument with one of the method's parameter names. Note that the provided parameter name should have the exact casing as declared on the method. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
List\Internal\Combiner.cs(127,31): warning CA2208: Method UpdateResultList passes 'Reason' as the paramName argument to a ArgumentOutOfRangeException constructor. Replace this argument with one of the method's parameter names. Note that the provided parameter name should have the exact casing as declared on the method. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
Cache\Internal\DistinctCalculator.cs(54,39): error RCS1037: Remove trailing white-space. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
Cache\Internal\DistinctCalculator.cs(62,35): error RCS1037: Remove trailing white-space. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
List\Internal\Combiner.cs(127,31): warning CA2208: Method UpdateResultList passes 'Reason' as the paramName argument to a ArgumentOutOfRangeException constructor. Replace this argument with one of the method's parameter names. Note that the provided parameter name should have the exact casing as declared on the method. [d:\a\1\s\src\DynamicData\DynamicData.csproj]
List\Internal\DynamicCombiner.cs(139,31): warning CA2208: Method UpdateResultList pas
```

**Comment by lummoj** [comment]
Apologies, have removed trailing whitespace

**Comment by glennawatson** [comment]
Roland has been away lately so if he doesn't respond in the next day, I will get some other Dynamic Data regulars and myself to do a review.

**Comment by lummoj** [comment]
Thanks Glenn, I think this makes the DistinctCalculator more robust, perhaps for scenarios that weren't envisaged originally like duplicate keys.

My use case where I'm trying to produce a list of distinct child items from a list of parents where this is some overlap in the child items between parents.

```
ParentCache
.Connect()
.MergeMany(p => p.ChildrenCache.Connect())
.DistinctValues(v =>v)
```

This is where I came across the issue in the first place. Investigating further this is very similar to the `Or` logical combiners but I need this to be dynamic as the parentCache changes

**Comment by RolandPheasant** [comment]
This PR is great thanks and no reason not to merge.

Incidentally, the example code as stated is similar to using Or and that you have used MergeMany to compensate for a missing dynamic Or operator (or TransformMany) operator. There is a need for me to add new overloads of Or and TransformMany. Regardless, this fix will also apply when those operators have been implemented.

**Pull request merged**
